language: minimal
env:
  matrix:
  - PYTHON_VERSION="3.6"
  global:
    secure: Zw4AYqbM8v99R3yQLfcENj7GmVyUtKwQEctS3TW60N+YdDfTa2l2V5Y6I4kSAYdmWEstf8sGLZy3Y0PDKvrnBjn35GrRtdCWsQHVBSwi3hXqlmkQva5MnRCjbZlVUbdJ4N+8TusZfZXeGcfiKoWERv+lVGPwJBZSbmjevBpckzqs8ngDYf9wuOY3p4zAWo0lQy5aVuZEPyHNx7aSfBhZhRmCfc1XrD5gz+6daIOx8/8cxJ2hQAv3KaVg6sKEmWAvfhaYRGYDYi5YrOQvXtmUcQ3LapKVxuV/vpQsetU5k8aEkBcSPV+KqH0qCsRlVklLIukqSHFDdBpR3o8tej0KHhZkqU+edeGe6rQwuW9mJ9mIttdBgPysrXZ1RsPlVMA8rXvSp6nvVTxcq9VOXaK5eW4nxGCIWdJ/F48j08BtepO9E9iwQEDjWsHpolIVidm2X2i7AS2DZN4F6dqlvB7HhguNeWNKdXCjdJEZUvg8W//m03X3j9ICbgRF2hDU7dyK/V9gzMsWt6n7anYiLb552mW1KJQ3zPs4X673JHIj5M1uRLJrLLbMmnR5DHC0oiuAPgvGuP1qzeeAH28jAOi0bxgjw6XifhLtX6Z0i11HSsjhSFJX9L9MxFkK4kuqlxOufFH7CdAa4lFIt8vPZxrjsyh0mcHjv4ppZ0CVWFj8fTc=
before_install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
install:
- conda create -q -n test -c conda-forge python=$PYTHON_VERSION rdkit pytest tqdm
  pandas
- source activate test
- python -c "import rdkit.Chem"
- pip install -r requirements.txt
- pip install -e .
script:
- pytest tests/
deploy:
  provider: pypi
  user: wilsoa6
  password:
    secure: BW9aTfathsye4PiATTnCouEIGTVu4NTNJmfbZk3giscKw/jnM5LqlIpYYXkzCf3nufl/X4EXChtjpAJu7R4rZhwyfL1pU3DDiQo3O2oxc4LwURPp5sFUroIEFZ7Gg3GGIV8ke4V8Z9A2CqfO+DgLhVA0UR0RWTyP0dBSD3utdoW9knM84DpgkfqF/uS+v3xFuhdx01Xs7NY+fCneVKan7oDCNyS3zmB5EFReeHtonxuoOKhlIrAAh8jVR6GmNOv67+YpEwJ5fYdaBJ0X3qVXzwK0mK8gVhLYsVQ4nxxNihg9+f1PaMR7C/63fVFU406eCi8s/XQyjRHZ0PjqqgaKkbvTJVoQF8PkmHADJfufq9pfokDsDgPRR5mC9fr7nB6KuDigeSwcq2ODlhjYuzuSVIvqQBpu512VuyPDooc1CmSEy2Rf1Q3z1lozXN48dX2Ahl1H8Tqp2Zr8tkC0j1zzdL5KgkAof1DWGbqNISClcDfYJvQzQuVSAFGCRCzsqDdTEb4nZ1+I3i8LWi2epGHta3NG/pBWd97GjwEVHr1sfnQtHwvGRz7ASDosC47Ta9852B5a4XB6gXn2oIBDdyZ5OrNFRILCPj0GqnFUuAk+gkDot6YLMModrbHy1Pt0CRnHKXITD8Nlexf1cW2IQjP5koZl5sNi5tTQw+tQMAdZaAE=
  on:
    tags: true
